# Generated by Django 5.1.3 on 2024-11-29 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_customer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='author_image',
            field=models.ImageField(default='author_covers/default.jpg', upload_to='author_covers/'),
        ),
    ]
