# Generated by Django 4.2.12 on 2024-11-08 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_author_book_bookgenre_cartitem_customer_genre_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover_image',
            field=models.ImageField(upload_to=''),
        ),
    ]
