# Generated by Django 5.1.3 on 2024-12-02 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_cartitem_session_key_alter_cartitem_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='user',
            new_name='username',
        ),
    ]
