# Generated by Django 4.2.12 on 2024-11-08 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_alter_book_cover_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('publisher_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='dimensions',
            field=models.CharField(default='Unknown', max_length=50),
        ),
        migrations.AddField(
            model_name='book',
            name='language',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='book',
            name='page_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='publisher',
            field=models.ForeignKey(default='Unknown', on_delete=django.db.models.deletion.CASCADE, to='App.publisher'),
        ),
    ]
