# Generated by Django 4.2.12 on 2024-11-08 23:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_publisher_book_dimensions_book_language_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='publisher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='App.publisher'),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='publisher_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
    ]
