# Generated by Django 5.1.3 on 2024-12-02 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_rename_user_customer_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='username',
            new_name='user',
        ),
    ]
