# Generated by Django 4.2.12 on 2024-11-09 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_alter_book_publisher_alter_publisher_publisher_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='publisher',
        ),
        migrations.DeleteModel(
            name='Publisher',
        ),
    ]
