# Generated by Django 4.2.12 on 2024-11-09 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0008_remove_book_publisher_delete_publisher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='language',
            field=models.CharField(max_length=100),
        ),
    ]
