# Generated by Django 5.1.2 on 2024-11-28 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0009_alter_book_language'),
    ]

    operations = [
    ]
