# Generated by Django 5.1.2 on 2024-11-28 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0011_dimensions_alter_book_dimensions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('publisher_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField(blank=True, null=True)),
                ('website', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
